name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: 
          npm install 
      - name: Fix ava permissions
        run: chmod +x ./node_modules/.bin/ava  

      - name: Fix c8 permissions
        run: chmod +x ./node_modules/.bin/c8    
        
      - name: Verify dependencies
        run: npm ls

      - name: Run test
        run: npm test
        
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_ALEX }}
          api-key: ${{ secrets.RENDER_API_KEY_ALEX }}
