name: cicd

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download dependencies
        run: npm install

      - name: Run tests
        run: npm run test
steps:
- name: Checkout repo
uses: actions/checkout@v3
- name: Install dependencies
run: npm install
working-directory: nodejs-server-server-generated
- name: Run tests
run: npm test
working-directory: nodejs-server-server-generated
