name: CI/CD Pipeline

on: 
  push:
    branches:
      - main # Trigger CI/CD on pushes to the main branch

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: nodejs-server-server-generated
      - name: Run tests
        run: npm test
        working-directory: nodejs-server-server-generated

  
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

