name: cicd

on:
  push:
    branches:
      - main
      - Dev--George  

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  cd:
    runs-on: ubuntu-lates
    needs: ci
    steps:
      - name: Debug
        run: echo "CD job started"
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_DOOJY }}
          api-key: ${{ secrets.RENDER_API_KEY_DOOJY }}
      - name: Confirm Deployment
        run: echo "Deployment to Render completed successfully"