name: cicd

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: nodejs-server-server-generated
      - name: Run test
        run: npm test
        working-directory: nodejs-server-server-generated
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SHH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ~/nodejs-server-server-generated
            git rest --hard origin/main
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/gtoutzia/nodejs-server-server-generated main
            bash -c1 'npm install'
            bash -c1 'pm2 restart nodejs-server-server-generated
            
    
