name: CI/CD Pipeline

on: 
  push:
    branches:
      - main # Trigger CI/CD on pushes to the main branch

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: nodejs-server-server-generated
      - name: Run tests
        run: npm test
        working-directory: nodejs-server-server-generated

  cd:
    name: Continuous Deployment
    needs: ci # Ensure CD runs only after CI succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the version your app requires
      - name: Install dependencies
        run: npm install
        working-directory: nodejs-server-server-generated
      - name: Deploy to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

